In [53]:
import pandas as pd
import numpy as np
import math
from sklearn import linear_model

In [54]:
df=pd.read_csv("house.csv")
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [55]:
median_Bedroom=math.floor(df.Bedroom.median())

In [56]:
median_Bedroom

3

In [57]:
df.Bedroom.fillna(median_Bedroom)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: Bedroom, dtype: float64

In [58]:
df.Bedroom=df.Bedroom.fillna(median_Bedroom)

In [59]:
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [60]:
df.to_csv("house2.csv")

In [61]:
reg=linear_model.LinearRegression()

In [64]:
reg.fit(df[['Area','Bedroom','Age']],df.Price)

LinearRegression()

In [73]:
reg.intercept_

383724.9999999998

In [74]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [75]:
reg.predict([[3000,3,40]])

array([444400.])

In [76]:
reg.predict([[3000,3,20]])

array([580900.])